# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nmoek/kit_server_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nmoek/kit_server_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nmoek/kit_server_project/CMakeFiles /home/nmoek/kit_server_project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nmoek/kit_server_project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named echo_server

# Build rule for target.
echo_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echo_server
.PHONY : echo_server

# fast build rule for target.
echo_server/fast:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/build
.PHONY : echo_server/fast

#=============================================================================
# Target rules for targets named test_application

# Build rule for target.
test_application: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_application
.PHONY : test_application

# fast build rule for target.
test_application/fast:
	$(MAKE) -f CMakeFiles/test_application.dir/build.make CMakeFiles/test_application.dir/build
.PHONY : test_application/fast

#=============================================================================
# Target rules for targets named test_env

# Build rule for target.
test_env: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_env
.PHONY : test_env

# fast build rule for target.
test_env/fast:
	$(MAKE) -f CMakeFiles/test_env.dir/build.make CMakeFiles/test_env.dir/build
.PHONY : test_env/fast

#=============================================================================
# Target rules for targets named test_daemon

# Build rule for target.
test_daemon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_daemon
.PHONY : test_daemon

# fast build rule for target.
test_daemon/fast:
	$(MAKE) -f CMakeFiles/test_daemon.dir/build.make CMakeFiles/test_daemon.dir/build
.PHONY : test_daemon/fast

#=============================================================================
# Target rules for targets named test_http_connection

# Build rule for target.
test_http_connection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_connection
.PHONY : test_http_connection

# fast build rule for target.
test_http_connection/fast:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/build
.PHONY : test_http_connection/fast

#=============================================================================
# Target rules for targets named test_http_server

# Build rule for target.
test_http_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_server
.PHONY : test_http_server

# fast build rule for target.
test_http_server/fast:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/build
.PHONY : test_http_server/fast

#=============================================================================
# Target rules for targets named test_tcp_server

# Build rule for target.
test_tcp_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tcp_server
.PHONY : test_tcp_server

# fast build rule for target.
test_tcp_server/fast:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/build
.PHONY : test_tcp_server/fast

#=============================================================================
# Target rules for targets named test_http_parser

# Build rule for target.
test_http_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_parser
.PHONY : test_http_parser

# fast build rule for target.
test_http_parser/fast:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/build
.PHONY : test_http_parser/fast

#=============================================================================
# Target rules for targets named test_http

# Build rule for target.
test_http: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http
.PHONY : test_http

# fast build rule for target.
test_http/fast:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/build
.PHONY : test_http/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test_uri

# Build rule for target.
test_uri: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_uri
.PHONY : test_uri

# fast build rule for target.
test_uri/fast:
	$(MAKE) -f CMakeFiles/test_uri.dir/build.make CMakeFiles/test_uri.dir/build
.PHONY : test_uri/fast

#=============================================================================
# Target rules for targets named test_coroutine

# Build rule for target.
test_coroutine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_coroutine
.PHONY : test_coroutine

# fast build rule for target.
test_coroutine/fast:
	$(MAKE) -f CMakeFiles/test_coroutine.dir/build.make CMakeFiles/test_coroutine.dir/build
.PHONY : test_coroutine/fast

#=============================================================================
# Target rules for targets named my_http_server

# Build rule for target.
my_http_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my_http_server
.PHONY : my_http_server

# fast build rule for target.
my_http_server/fast:
	$(MAKE) -f CMakeFiles/my_http_server.dir/build.make CMakeFiles/my_http_server.dir/build
.PHONY : my_http_server/fast

#=============================================================================
# Target rules for targets named test_addr

# Build rule for target.
test_addr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_addr
.PHONY : test_addr

# fast build rule for target.
test_addr/fast:
	$(MAKE) -f CMakeFiles/test_addr.dir/build.make CMakeFiles/test_addr.dir/build
.PHONY : test_addr/fast

#=============================================================================
# Target rules for targets named test_bytearray

# Build rule for target.
test_bytearray: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_bytearray
.PHONY : test_bytearray

# fast build rule for target.
test_bytearray/fast:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/build
.PHONY : test_bytearray/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_schedule

# Build rule for target.
test_schedule: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_schedule
.PHONY : test_schedule

# fast build rule for target.
test_schedule/fast:
	$(MAKE) -f CMakeFiles/test_schedule.dir/build.make CMakeFiles/test_schedule.dir/build
.PHONY : test_schedule/fast

#=============================================================================
# Target rules for targets named test_utils

# Build rule for target.
test_utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_utils
.PHONY : test_utils

# fast build rule for target.
test_utils/fast:
	$(MAKE) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/build
.PHONY : test_utils/fast

#=============================================================================
# Target rules for targets named test_iomanager

# Build rule for target.
test_iomanager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_iomanager
.PHONY : test_iomanager

# fast build rule for target.
test_iomanager/fast:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/build
.PHONY : test_iomanager/fast

#=============================================================================
# Target rules for targets named test_thread

# Build rule for target.
test_thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_thread
.PHONY : test_thread

# fast build rule for target.
test_thread/fast:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/build
.PHONY : test_thread/fast

#=============================================================================
# Target rules for targets named test_timer

# Build rule for target.
test_timer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_timer
.PHONY : test_timer

# fast build rule for target.
test_timer/fast:
	$(MAKE) -f CMakeFiles/test_timer.dir/build.make CMakeFiles/test_timer.dir/build
.PHONY : test_timer/fast

#=============================================================================
# Target rules for targets named test_hook

# Build rule for target.
test_hook: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hook
.PHONY : test_hook

# fast build rule for target.
test_hook/fast:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/build
.PHONY : test_hook/fast

#=============================================================================
# Target rules for targets named kit_server

# Build rule for target.
kit_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kit_server
.PHONY : kit_server

# fast build rule for target.
kit_server/fast:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/build
.PHONY : kit_server/fast

#=============================================================================
# Target rules for targets named test_socket

# Build rule for target.
test_socket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_socket
.PHONY : test_socket

# fast build rule for target.
test_socket/fast:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/build
.PHONY : test_socket/fast

ab_example/my_http_server.o: ab_example/my_http_server.cpp.o

.PHONY : ab_example/my_http_server.o

# target to build an object file
ab_example/my_http_server.cpp.o:
	$(MAKE) -f CMakeFiles/my_http_server.dir/build.make CMakeFiles/my_http_server.dir/ab_example/my_http_server.cpp.o
.PHONY : ab_example/my_http_server.cpp.o

ab_example/my_http_server.i: ab_example/my_http_server.cpp.i

.PHONY : ab_example/my_http_server.i

# target to preprocess a source file
ab_example/my_http_server.cpp.i:
	$(MAKE) -f CMakeFiles/my_http_server.dir/build.make CMakeFiles/my_http_server.dir/ab_example/my_http_server.cpp.i
.PHONY : ab_example/my_http_server.cpp.i

ab_example/my_http_server.s: ab_example/my_http_server.cpp.s

.PHONY : ab_example/my_http_server.s

# target to generate assembly for a file
ab_example/my_http_server.cpp.s:
	$(MAKE) -f CMakeFiles/my_http_server.dir/build.make CMakeFiles/my_http_server.dir/ab_example/my_http_server.cpp.s
.PHONY : ab_example/my_http_server.cpp.s

example/echo_server.o: example/echo_server.cpp.o

.PHONY : example/echo_server.o

# target to build an object file
example/echo_server.cpp.o:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/example/echo_server.cpp.o
.PHONY : example/echo_server.cpp.o

example/echo_server.i: example/echo_server.cpp.i

.PHONY : example/echo_server.i

# target to preprocess a source file
example/echo_server.cpp.i:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/example/echo_server.cpp.i
.PHONY : example/echo_server.cpp.i

example/echo_server.s: example/echo_server.cpp.s

.PHONY : example/echo_server.s

# target to generate assembly for a file
example/echo_server.cpp.s:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/example/echo_server.cpp.s
.PHONY : example/echo_server.cpp.s

kit_server/Log.o: kit_server/Log.cpp.o

.PHONY : kit_server/Log.o

# target to build an object file
kit_server/Log.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/Log.cpp.o
.PHONY : kit_server/Log.cpp.o

kit_server/Log.i: kit_server/Log.cpp.i

.PHONY : kit_server/Log.i

# target to preprocess a source file
kit_server/Log.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/Log.cpp.i
.PHONY : kit_server/Log.cpp.i

kit_server/Log.s: kit_server/Log.cpp.s

.PHONY : kit_server/Log.s

# target to generate assembly for a file
kit_server/Log.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/Log.cpp.s
.PHONY : kit_server/Log.cpp.s

kit_server/address.o: kit_server/address.cpp.o

.PHONY : kit_server/address.o

# target to build an object file
kit_server/address.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/address.cpp.o
.PHONY : kit_server/address.cpp.o

kit_server/address.i: kit_server/address.cpp.i

.PHONY : kit_server/address.i

# target to preprocess a source file
kit_server/address.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/address.cpp.i
.PHONY : kit_server/address.cpp.i

kit_server/address.s: kit_server/address.cpp.s

.PHONY : kit_server/address.s

# target to generate assembly for a file
kit_server/address.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/address.cpp.s
.PHONY : kit_server/address.cpp.s

kit_server/application.o: kit_server/application.cpp.o

.PHONY : kit_server/application.o

# target to build an object file
kit_server/application.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/application.cpp.o
.PHONY : kit_server/application.cpp.o

kit_server/application.i: kit_server/application.cpp.i

.PHONY : kit_server/application.i

# target to preprocess a source file
kit_server/application.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/application.cpp.i
.PHONY : kit_server/application.cpp.i

kit_server/application.s: kit_server/application.cpp.s

.PHONY : kit_server/application.s

# target to generate assembly for a file
kit_server/application.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/application.cpp.s
.PHONY : kit_server/application.cpp.s

kit_server/bytearray.o: kit_server/bytearray.cpp.o

.PHONY : kit_server/bytearray.o

# target to build an object file
kit_server/bytearray.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/bytearray.cpp.o
.PHONY : kit_server/bytearray.cpp.o

kit_server/bytearray.i: kit_server/bytearray.cpp.i

.PHONY : kit_server/bytearray.i

# target to preprocess a source file
kit_server/bytearray.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/bytearray.cpp.i
.PHONY : kit_server/bytearray.cpp.i

kit_server/bytearray.s: kit_server/bytearray.cpp.s

.PHONY : kit_server/bytearray.s

# target to generate assembly for a file
kit_server/bytearray.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/bytearray.cpp.s
.PHONY : kit_server/bytearray.cpp.s

kit_server/config.o: kit_server/config.cpp.o

.PHONY : kit_server/config.o

# target to build an object file
kit_server/config.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/config.cpp.o
.PHONY : kit_server/config.cpp.o

kit_server/config.i: kit_server/config.cpp.i

.PHONY : kit_server/config.i

# target to preprocess a source file
kit_server/config.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/config.cpp.i
.PHONY : kit_server/config.cpp.i

kit_server/config.s: kit_server/config.cpp.s

.PHONY : kit_server/config.s

# target to generate assembly for a file
kit_server/config.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/config.cpp.s
.PHONY : kit_server/config.cpp.s

kit_server/coroutine.o: kit_server/coroutine.cpp.o

.PHONY : kit_server/coroutine.o

# target to build an object file
kit_server/coroutine.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/coroutine.cpp.o
.PHONY : kit_server/coroutine.cpp.o

kit_server/coroutine.i: kit_server/coroutine.cpp.i

.PHONY : kit_server/coroutine.i

# target to preprocess a source file
kit_server/coroutine.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/coroutine.cpp.i
.PHONY : kit_server/coroutine.cpp.i

kit_server/coroutine.s: kit_server/coroutine.cpp.s

.PHONY : kit_server/coroutine.s

# target to generate assembly for a file
kit_server/coroutine.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/coroutine.cpp.s
.PHONY : kit_server/coroutine.cpp.s

kit_server/daemon.o: kit_server/daemon.cpp.o

.PHONY : kit_server/daemon.o

# target to build an object file
kit_server/daemon.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/daemon.cpp.o
.PHONY : kit_server/daemon.cpp.o

kit_server/daemon.i: kit_server/daemon.cpp.i

.PHONY : kit_server/daemon.i

# target to preprocess a source file
kit_server/daemon.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/daemon.cpp.i
.PHONY : kit_server/daemon.cpp.i

kit_server/daemon.s: kit_server/daemon.cpp.s

.PHONY : kit_server/daemon.s

# target to generate assembly for a file
kit_server/daemon.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/daemon.cpp.s
.PHONY : kit_server/daemon.cpp.s

kit_server/env.o: kit_server/env.cpp.o

.PHONY : kit_server/env.o

# target to build an object file
kit_server/env.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/env.cpp.o
.PHONY : kit_server/env.cpp.o

kit_server/env.i: kit_server/env.cpp.i

.PHONY : kit_server/env.i

# target to preprocess a source file
kit_server/env.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/env.cpp.i
.PHONY : kit_server/env.cpp.i

kit_server/env.s: kit_server/env.cpp.s

.PHONY : kit_server/env.s

# target to generate assembly for a file
kit_server/env.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/env.cpp.s
.PHONY : kit_server/env.cpp.s

kit_server/fdmanager.o: kit_server/fdmanager.cpp.o

.PHONY : kit_server/fdmanager.o

# target to build an object file
kit_server/fdmanager.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/fdmanager.cpp.o
.PHONY : kit_server/fdmanager.cpp.o

kit_server/fdmanager.i: kit_server/fdmanager.cpp.i

.PHONY : kit_server/fdmanager.i

# target to preprocess a source file
kit_server/fdmanager.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/fdmanager.cpp.i
.PHONY : kit_server/fdmanager.cpp.i

kit_server/fdmanager.s: kit_server/fdmanager.cpp.s

.PHONY : kit_server/fdmanager.s

# target to generate assembly for a file
kit_server/fdmanager.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/fdmanager.cpp.s
.PHONY : kit_server/fdmanager.cpp.s

kit_server/hook.o: kit_server/hook.cpp.o

.PHONY : kit_server/hook.o

# target to build an object file
kit_server/hook.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/hook.cpp.o
.PHONY : kit_server/hook.cpp.o

kit_server/hook.i: kit_server/hook.cpp.i

.PHONY : kit_server/hook.i

# target to preprocess a source file
kit_server/hook.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/hook.cpp.i
.PHONY : kit_server/hook.cpp.i

kit_server/hook.s: kit_server/hook.cpp.s

.PHONY : kit_server/hook.s

# target to generate assembly for a file
kit_server/hook.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/hook.cpp.s
.PHONY : kit_server/hook.cpp.s

kit_server/http/http.o: kit_server/http/http.cpp.o

.PHONY : kit_server/http/http.o

# target to build an object file
kit_server/http/http.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/http.cpp.o
.PHONY : kit_server/http/http.cpp.o

kit_server/http/http.i: kit_server/http/http.cpp.i

.PHONY : kit_server/http/http.i

# target to preprocess a source file
kit_server/http/http.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/http.cpp.i
.PHONY : kit_server/http/http.cpp.i

kit_server/http/http.s: kit_server/http/http.cpp.s

.PHONY : kit_server/http/http.s

# target to generate assembly for a file
kit_server/http/http.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/http.cpp.s
.PHONY : kit_server/http/http.cpp.s

kit_server/http/http11_parser.rl.o: kit_server/http/http11_parser.rl.cpp.o

.PHONY : kit_server/http/http11_parser.rl.o

# target to build an object file
kit_server/http/http11_parser.rl.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/http11_parser.rl.cpp.o
.PHONY : kit_server/http/http11_parser.rl.cpp.o

kit_server/http/http11_parser.rl.i: kit_server/http/http11_parser.rl.cpp.i

.PHONY : kit_server/http/http11_parser.rl.i

# target to preprocess a source file
kit_server/http/http11_parser.rl.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/http11_parser.rl.cpp.i
.PHONY : kit_server/http/http11_parser.rl.cpp.i

kit_server/http/http11_parser.rl.s: kit_server/http/http11_parser.rl.cpp.s

.PHONY : kit_server/http/http11_parser.rl.s

# target to generate assembly for a file
kit_server/http/http11_parser.rl.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/http11_parser.rl.cpp.s
.PHONY : kit_server/http/http11_parser.rl.cpp.s

kit_server/http/http_connection.o: kit_server/http/http_connection.cpp.o

.PHONY : kit_server/http/http_connection.o

# target to build an object file
kit_server/http/http_connection.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/http_connection.cpp.o
.PHONY : kit_server/http/http_connection.cpp.o

kit_server/http/http_connection.i: kit_server/http/http_connection.cpp.i

.PHONY : kit_server/http/http_connection.i

# target to preprocess a source file
kit_server/http/http_connection.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/http_connection.cpp.i
.PHONY : kit_server/http/http_connection.cpp.i

kit_server/http/http_connection.s: kit_server/http/http_connection.cpp.s

.PHONY : kit_server/http/http_connection.s

# target to generate assembly for a file
kit_server/http/http_connection.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/http_connection.cpp.s
.PHONY : kit_server/http/http_connection.cpp.s

kit_server/http/http_parser.o: kit_server/http/http_parser.cpp.o

.PHONY : kit_server/http/http_parser.o

# target to build an object file
kit_server/http/http_parser.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/http_parser.cpp.o
.PHONY : kit_server/http/http_parser.cpp.o

kit_server/http/http_parser.i: kit_server/http/http_parser.cpp.i

.PHONY : kit_server/http/http_parser.i

# target to preprocess a source file
kit_server/http/http_parser.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/http_parser.cpp.i
.PHONY : kit_server/http/http_parser.cpp.i

kit_server/http/http_parser.s: kit_server/http/http_parser.cpp.s

.PHONY : kit_server/http/http_parser.s

# target to generate assembly for a file
kit_server/http/http_parser.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/http_parser.cpp.s
.PHONY : kit_server/http/http_parser.cpp.s

kit_server/http/http_server.o: kit_server/http/http_server.cpp.o

.PHONY : kit_server/http/http_server.o

# target to build an object file
kit_server/http/http_server.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/http_server.cpp.o
.PHONY : kit_server/http/http_server.cpp.o

kit_server/http/http_server.i: kit_server/http/http_server.cpp.i

.PHONY : kit_server/http/http_server.i

# target to preprocess a source file
kit_server/http/http_server.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/http_server.cpp.i
.PHONY : kit_server/http/http_server.cpp.i

kit_server/http/http_server.s: kit_server/http/http_server.cpp.s

.PHONY : kit_server/http/http_server.s

# target to generate assembly for a file
kit_server/http/http_server.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/http_server.cpp.s
.PHONY : kit_server/http/http_server.cpp.s

kit_server/http/http_session.o: kit_server/http/http_session.cpp.o

.PHONY : kit_server/http/http_session.o

# target to build an object file
kit_server/http/http_session.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/http_session.cpp.o
.PHONY : kit_server/http/http_session.cpp.o

kit_server/http/http_session.i: kit_server/http/http_session.cpp.i

.PHONY : kit_server/http/http_session.i

# target to preprocess a source file
kit_server/http/http_session.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/http_session.cpp.i
.PHONY : kit_server/http/http_session.cpp.i

kit_server/http/http_session.s: kit_server/http/http_session.cpp.s

.PHONY : kit_server/http/http_session.s

# target to generate assembly for a file
kit_server/http/http_session.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/http_session.cpp.s
.PHONY : kit_server/http/http_session.cpp.s

kit_server/http/httpclient_parser.rl.o: kit_server/http/httpclient_parser.rl.cpp.o

.PHONY : kit_server/http/httpclient_parser.rl.o

# target to build an object file
kit_server/http/httpclient_parser.rl.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/httpclient_parser.rl.cpp.o
.PHONY : kit_server/http/httpclient_parser.rl.cpp.o

kit_server/http/httpclient_parser.rl.i: kit_server/http/httpclient_parser.rl.cpp.i

.PHONY : kit_server/http/httpclient_parser.rl.i

# target to preprocess a source file
kit_server/http/httpclient_parser.rl.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/httpclient_parser.rl.cpp.i
.PHONY : kit_server/http/httpclient_parser.rl.cpp.i

kit_server/http/httpclient_parser.rl.s: kit_server/http/httpclient_parser.rl.cpp.s

.PHONY : kit_server/http/httpclient_parser.rl.s

# target to generate assembly for a file
kit_server/http/httpclient_parser.rl.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/httpclient_parser.rl.cpp.s
.PHONY : kit_server/http/httpclient_parser.rl.cpp.s

kit_server/http/servlet.o: kit_server/http/servlet.cpp.o

.PHONY : kit_server/http/servlet.o

# target to build an object file
kit_server/http/servlet.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/servlet.cpp.o
.PHONY : kit_server/http/servlet.cpp.o

kit_server/http/servlet.i: kit_server/http/servlet.cpp.i

.PHONY : kit_server/http/servlet.i

# target to preprocess a source file
kit_server/http/servlet.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/servlet.cpp.i
.PHONY : kit_server/http/servlet.cpp.i

kit_server/http/servlet.s: kit_server/http/servlet.cpp.s

.PHONY : kit_server/http/servlet.s

# target to generate assembly for a file
kit_server/http/servlet.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/http/servlet.cpp.s
.PHONY : kit_server/http/servlet.cpp.s

kit_server/iomanager.o: kit_server/iomanager.cpp.o

.PHONY : kit_server/iomanager.o

# target to build an object file
kit_server/iomanager.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/iomanager.cpp.o
.PHONY : kit_server/iomanager.cpp.o

kit_server/iomanager.i: kit_server/iomanager.cpp.i

.PHONY : kit_server/iomanager.i

# target to preprocess a source file
kit_server/iomanager.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/iomanager.cpp.i
.PHONY : kit_server/iomanager.cpp.i

kit_server/iomanager.s: kit_server/iomanager.cpp.s

.PHONY : kit_server/iomanager.s

# target to generate assembly for a file
kit_server/iomanager.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/iomanager.cpp.s
.PHONY : kit_server/iomanager.cpp.s

kit_server/mutex.o: kit_server/mutex.cpp.o

.PHONY : kit_server/mutex.o

# target to build an object file
kit_server/mutex.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/mutex.cpp.o
.PHONY : kit_server/mutex.cpp.o

kit_server/mutex.i: kit_server/mutex.cpp.i

.PHONY : kit_server/mutex.i

# target to preprocess a source file
kit_server/mutex.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/mutex.cpp.i
.PHONY : kit_server/mutex.cpp.i

kit_server/mutex.s: kit_server/mutex.cpp.s

.PHONY : kit_server/mutex.s

# target to generate assembly for a file
kit_server/mutex.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/mutex.cpp.s
.PHONY : kit_server/mutex.cpp.s

kit_server/scheduler.o: kit_server/scheduler.cpp.o

.PHONY : kit_server/scheduler.o

# target to build an object file
kit_server/scheduler.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/scheduler.cpp.o
.PHONY : kit_server/scheduler.cpp.o

kit_server/scheduler.i: kit_server/scheduler.cpp.i

.PHONY : kit_server/scheduler.i

# target to preprocess a source file
kit_server/scheduler.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/scheduler.cpp.i
.PHONY : kit_server/scheduler.cpp.i

kit_server/scheduler.s: kit_server/scheduler.cpp.s

.PHONY : kit_server/scheduler.s

# target to generate assembly for a file
kit_server/scheduler.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/scheduler.cpp.s
.PHONY : kit_server/scheduler.cpp.s

kit_server/socket.o: kit_server/socket.cpp.o

.PHONY : kit_server/socket.o

# target to build an object file
kit_server/socket.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/socket.cpp.o
.PHONY : kit_server/socket.cpp.o

kit_server/socket.i: kit_server/socket.cpp.i

.PHONY : kit_server/socket.i

# target to preprocess a source file
kit_server/socket.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/socket.cpp.i
.PHONY : kit_server/socket.cpp.i

kit_server/socket.s: kit_server/socket.cpp.s

.PHONY : kit_server/socket.s

# target to generate assembly for a file
kit_server/socket.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/socket.cpp.s
.PHONY : kit_server/socket.cpp.s

kit_server/socket_stream.o: kit_server/socket_stream.cpp.o

.PHONY : kit_server/socket_stream.o

# target to build an object file
kit_server/socket_stream.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/socket_stream.cpp.o
.PHONY : kit_server/socket_stream.cpp.o

kit_server/socket_stream.i: kit_server/socket_stream.cpp.i

.PHONY : kit_server/socket_stream.i

# target to preprocess a source file
kit_server/socket_stream.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/socket_stream.cpp.i
.PHONY : kit_server/socket_stream.cpp.i

kit_server/socket_stream.s: kit_server/socket_stream.cpp.s

.PHONY : kit_server/socket_stream.s

# target to generate assembly for a file
kit_server/socket_stream.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/socket_stream.cpp.s
.PHONY : kit_server/socket_stream.cpp.s

kit_server/stream.o: kit_server/stream.cpp.o

.PHONY : kit_server/stream.o

# target to build an object file
kit_server/stream.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/stream.cpp.o
.PHONY : kit_server/stream.cpp.o

kit_server/stream.i: kit_server/stream.cpp.i

.PHONY : kit_server/stream.i

# target to preprocess a source file
kit_server/stream.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/stream.cpp.i
.PHONY : kit_server/stream.cpp.i

kit_server/stream.s: kit_server/stream.cpp.s

.PHONY : kit_server/stream.s

# target to generate assembly for a file
kit_server/stream.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/stream.cpp.s
.PHONY : kit_server/stream.cpp.s

kit_server/tcp_server.o: kit_server/tcp_server.cpp.o

.PHONY : kit_server/tcp_server.o

# target to build an object file
kit_server/tcp_server.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/tcp_server.cpp.o
.PHONY : kit_server/tcp_server.cpp.o

kit_server/tcp_server.i: kit_server/tcp_server.cpp.i

.PHONY : kit_server/tcp_server.i

# target to preprocess a source file
kit_server/tcp_server.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/tcp_server.cpp.i
.PHONY : kit_server/tcp_server.cpp.i

kit_server/tcp_server.s: kit_server/tcp_server.cpp.s

.PHONY : kit_server/tcp_server.s

# target to generate assembly for a file
kit_server/tcp_server.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/tcp_server.cpp.s
.PHONY : kit_server/tcp_server.cpp.s

kit_server/thread.o: kit_server/thread.cpp.o

.PHONY : kit_server/thread.o

# target to build an object file
kit_server/thread.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/thread.cpp.o
.PHONY : kit_server/thread.cpp.o

kit_server/thread.i: kit_server/thread.cpp.i

.PHONY : kit_server/thread.i

# target to preprocess a source file
kit_server/thread.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/thread.cpp.i
.PHONY : kit_server/thread.cpp.i

kit_server/thread.s: kit_server/thread.cpp.s

.PHONY : kit_server/thread.s

# target to generate assembly for a file
kit_server/thread.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/thread.cpp.s
.PHONY : kit_server/thread.cpp.s

kit_server/timer.o: kit_server/timer.cpp.o

.PHONY : kit_server/timer.o

# target to build an object file
kit_server/timer.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/timer.cpp.o
.PHONY : kit_server/timer.cpp.o

kit_server/timer.i: kit_server/timer.cpp.i

.PHONY : kit_server/timer.i

# target to preprocess a source file
kit_server/timer.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/timer.cpp.i
.PHONY : kit_server/timer.cpp.i

kit_server/timer.s: kit_server/timer.cpp.s

.PHONY : kit_server/timer.s

# target to generate assembly for a file
kit_server/timer.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/timer.cpp.s
.PHONY : kit_server/timer.cpp.s

kit_server/uri.rl.o: kit_server/uri.rl.cpp.o

.PHONY : kit_server/uri.rl.o

# target to build an object file
kit_server/uri.rl.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/uri.rl.cpp.o
.PHONY : kit_server/uri.rl.cpp.o

kit_server/uri.rl.i: kit_server/uri.rl.cpp.i

.PHONY : kit_server/uri.rl.i

# target to preprocess a source file
kit_server/uri.rl.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/uri.rl.cpp.i
.PHONY : kit_server/uri.rl.cpp.i

kit_server/uri.rl.s: kit_server/uri.rl.cpp.s

.PHONY : kit_server/uri.rl.s

# target to generate assembly for a file
kit_server/uri.rl.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/uri.rl.cpp.s
.PHONY : kit_server/uri.rl.cpp.s

kit_server/util.o: kit_server/util.cpp.o

.PHONY : kit_server/util.o

# target to build an object file
kit_server/util.cpp.o:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/util.cpp.o
.PHONY : kit_server/util.cpp.o

kit_server/util.i: kit_server/util.cpp.i

.PHONY : kit_server/util.i

# target to preprocess a source file
kit_server/util.cpp.i:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/util.cpp.i
.PHONY : kit_server/util.cpp.i

kit_server/util.s: kit_server/util.cpp.s

.PHONY : kit_server/util.s

# target to generate assembly for a file
kit_server/util.cpp.s:
	$(MAKE) -f CMakeFiles/kit_server.dir/build.make CMakeFiles/kit_server.dir/kit_server/util.cpp.s
.PHONY : kit_server/util.cpp.s

tests/test.o: tests/test.cpp.o

.PHONY : tests/test.o

# target to build an object file
tests/test.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cpp.o
.PHONY : tests/test.cpp.o

tests/test.i: tests/test.cpp.i

.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cpp.i
.PHONY : tests/test.cpp.i

tests/test.s: tests/test.cpp.s

.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cpp.s
.PHONY : tests/test.cpp.s

tests/test_addr.o: tests/test_addr.cpp.o

.PHONY : tests/test_addr.o

# target to build an object file
tests/test_addr.cpp.o:
	$(MAKE) -f CMakeFiles/test_addr.dir/build.make CMakeFiles/test_addr.dir/tests/test_addr.cpp.o
.PHONY : tests/test_addr.cpp.o

tests/test_addr.i: tests/test_addr.cpp.i

.PHONY : tests/test_addr.i

# target to preprocess a source file
tests/test_addr.cpp.i:
	$(MAKE) -f CMakeFiles/test_addr.dir/build.make CMakeFiles/test_addr.dir/tests/test_addr.cpp.i
.PHONY : tests/test_addr.cpp.i

tests/test_addr.s: tests/test_addr.cpp.s

.PHONY : tests/test_addr.s

# target to generate assembly for a file
tests/test_addr.cpp.s:
	$(MAKE) -f CMakeFiles/test_addr.dir/build.make CMakeFiles/test_addr.dir/tests/test_addr.cpp.s
.PHONY : tests/test_addr.cpp.s

tests/test_application.o: tests/test_application.cpp.o

.PHONY : tests/test_application.o

# target to build an object file
tests/test_application.cpp.o:
	$(MAKE) -f CMakeFiles/test_application.dir/build.make CMakeFiles/test_application.dir/tests/test_application.cpp.o
.PHONY : tests/test_application.cpp.o

tests/test_application.i: tests/test_application.cpp.i

.PHONY : tests/test_application.i

# target to preprocess a source file
tests/test_application.cpp.i:
	$(MAKE) -f CMakeFiles/test_application.dir/build.make CMakeFiles/test_application.dir/tests/test_application.cpp.i
.PHONY : tests/test_application.cpp.i

tests/test_application.s: tests/test_application.cpp.s

.PHONY : tests/test_application.s

# target to generate assembly for a file
tests/test_application.cpp.s:
	$(MAKE) -f CMakeFiles/test_application.dir/build.make CMakeFiles/test_application.dir/tests/test_application.cpp.s
.PHONY : tests/test_application.cpp.s

tests/test_bytearray.o: tests/test_bytearray.cpp.o

.PHONY : tests/test_bytearray.o

# target to build an object file
tests/test_bytearray.cpp.o:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cpp.o
.PHONY : tests/test_bytearray.cpp.o

tests/test_bytearray.i: tests/test_bytearray.cpp.i

.PHONY : tests/test_bytearray.i

# target to preprocess a source file
tests/test_bytearray.cpp.i:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cpp.i
.PHONY : tests/test_bytearray.cpp.i

tests/test_bytearray.s: tests/test_bytearray.cpp.s

.PHONY : tests/test_bytearray.s

# target to generate assembly for a file
tests/test_bytearray.cpp.s:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cpp.s
.PHONY : tests/test_bytearray.cpp.s

tests/test_config.o: tests/test_config.cpp.o

.PHONY : tests/test_config.o

# target to build an object file
tests/test_config.cpp.o:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cpp.o
.PHONY : tests/test_config.cpp.o

tests/test_config.i: tests/test_config.cpp.i

.PHONY : tests/test_config.i

# target to preprocess a source file
tests/test_config.cpp.i:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cpp.i
.PHONY : tests/test_config.cpp.i

tests/test_config.s: tests/test_config.cpp.s

.PHONY : tests/test_config.s

# target to generate assembly for a file
tests/test_config.cpp.s:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cpp.s
.PHONY : tests/test_config.cpp.s

tests/test_coroutine.o: tests/test_coroutine.cpp.o

.PHONY : tests/test_coroutine.o

# target to build an object file
tests/test_coroutine.cpp.o:
	$(MAKE) -f CMakeFiles/test_coroutine.dir/build.make CMakeFiles/test_coroutine.dir/tests/test_coroutine.cpp.o
.PHONY : tests/test_coroutine.cpp.o

tests/test_coroutine.i: tests/test_coroutine.cpp.i

.PHONY : tests/test_coroutine.i

# target to preprocess a source file
tests/test_coroutine.cpp.i:
	$(MAKE) -f CMakeFiles/test_coroutine.dir/build.make CMakeFiles/test_coroutine.dir/tests/test_coroutine.cpp.i
.PHONY : tests/test_coroutine.cpp.i

tests/test_coroutine.s: tests/test_coroutine.cpp.s

.PHONY : tests/test_coroutine.s

# target to generate assembly for a file
tests/test_coroutine.cpp.s:
	$(MAKE) -f CMakeFiles/test_coroutine.dir/build.make CMakeFiles/test_coroutine.dir/tests/test_coroutine.cpp.s
.PHONY : tests/test_coroutine.cpp.s

tests/test_daemon.o: tests/test_daemon.cpp.o

.PHONY : tests/test_daemon.o

# target to build an object file
tests/test_daemon.cpp.o:
	$(MAKE) -f CMakeFiles/test_daemon.dir/build.make CMakeFiles/test_daemon.dir/tests/test_daemon.cpp.o
.PHONY : tests/test_daemon.cpp.o

tests/test_daemon.i: tests/test_daemon.cpp.i

.PHONY : tests/test_daemon.i

# target to preprocess a source file
tests/test_daemon.cpp.i:
	$(MAKE) -f CMakeFiles/test_daemon.dir/build.make CMakeFiles/test_daemon.dir/tests/test_daemon.cpp.i
.PHONY : tests/test_daemon.cpp.i

tests/test_daemon.s: tests/test_daemon.cpp.s

.PHONY : tests/test_daemon.s

# target to generate assembly for a file
tests/test_daemon.cpp.s:
	$(MAKE) -f CMakeFiles/test_daemon.dir/build.make CMakeFiles/test_daemon.dir/tests/test_daemon.cpp.s
.PHONY : tests/test_daemon.cpp.s

tests/test_env.o: tests/test_env.cpp.o

.PHONY : tests/test_env.o

# target to build an object file
tests/test_env.cpp.o:
	$(MAKE) -f CMakeFiles/test_env.dir/build.make CMakeFiles/test_env.dir/tests/test_env.cpp.o
.PHONY : tests/test_env.cpp.o

tests/test_env.i: tests/test_env.cpp.i

.PHONY : tests/test_env.i

# target to preprocess a source file
tests/test_env.cpp.i:
	$(MAKE) -f CMakeFiles/test_env.dir/build.make CMakeFiles/test_env.dir/tests/test_env.cpp.i
.PHONY : tests/test_env.cpp.i

tests/test_env.s: tests/test_env.cpp.s

.PHONY : tests/test_env.s

# target to generate assembly for a file
tests/test_env.cpp.s:
	$(MAKE) -f CMakeFiles/test_env.dir/build.make CMakeFiles/test_env.dir/tests/test_env.cpp.s
.PHONY : tests/test_env.cpp.s

tests/test_hook.o: tests/test_hook.cpp.o

.PHONY : tests/test_hook.o

# target to build an object file
tests/test_hook.cpp.o:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cpp.o
.PHONY : tests/test_hook.cpp.o

tests/test_hook.i: tests/test_hook.cpp.i

.PHONY : tests/test_hook.i

# target to preprocess a source file
tests/test_hook.cpp.i:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cpp.i
.PHONY : tests/test_hook.cpp.i

tests/test_hook.s: tests/test_hook.cpp.s

.PHONY : tests/test_hook.s

# target to generate assembly for a file
tests/test_hook.cpp.s:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cpp.s
.PHONY : tests/test_hook.cpp.s

tests/test_http.o: tests/test_http.cpp.o

.PHONY : tests/test_http.o

# target to build an object file
tests/test_http.cpp.o:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cpp.o
.PHONY : tests/test_http.cpp.o

tests/test_http.i: tests/test_http.cpp.i

.PHONY : tests/test_http.i

# target to preprocess a source file
tests/test_http.cpp.i:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cpp.i
.PHONY : tests/test_http.cpp.i

tests/test_http.s: tests/test_http.cpp.s

.PHONY : tests/test_http.s

# target to generate assembly for a file
tests/test_http.cpp.s:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cpp.s
.PHONY : tests/test_http.cpp.s

tests/test_http_connection.o: tests/test_http_connection.cpp.o

.PHONY : tests/test_http_connection.o

# target to build an object file
tests/test_http_connection.cpp.o:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cpp.o
.PHONY : tests/test_http_connection.cpp.o

tests/test_http_connection.i: tests/test_http_connection.cpp.i

.PHONY : tests/test_http_connection.i

# target to preprocess a source file
tests/test_http_connection.cpp.i:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cpp.i
.PHONY : tests/test_http_connection.cpp.i

tests/test_http_connection.s: tests/test_http_connection.cpp.s

.PHONY : tests/test_http_connection.s

# target to generate assembly for a file
tests/test_http_connection.cpp.s:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cpp.s
.PHONY : tests/test_http_connection.cpp.s

tests/test_http_parser.o: tests/test_http_parser.cpp.o

.PHONY : tests/test_http_parser.o

# target to build an object file
tests/test_http_parser.cpp.o:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cpp.o
.PHONY : tests/test_http_parser.cpp.o

tests/test_http_parser.i: tests/test_http_parser.cpp.i

.PHONY : tests/test_http_parser.i

# target to preprocess a source file
tests/test_http_parser.cpp.i:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cpp.i
.PHONY : tests/test_http_parser.cpp.i

tests/test_http_parser.s: tests/test_http_parser.cpp.s

.PHONY : tests/test_http_parser.s

# target to generate assembly for a file
tests/test_http_parser.cpp.s:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cpp.s
.PHONY : tests/test_http_parser.cpp.s

tests/test_http_server.o: tests/test_http_server.cpp.o

.PHONY : tests/test_http_server.o

# target to build an object file
tests/test_http_server.cpp.o:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cpp.o
.PHONY : tests/test_http_server.cpp.o

tests/test_http_server.i: tests/test_http_server.cpp.i

.PHONY : tests/test_http_server.i

# target to preprocess a source file
tests/test_http_server.cpp.i:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cpp.i
.PHONY : tests/test_http_server.cpp.i

tests/test_http_server.s: tests/test_http_server.cpp.s

.PHONY : tests/test_http_server.s

# target to generate assembly for a file
tests/test_http_server.cpp.s:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cpp.s
.PHONY : tests/test_http_server.cpp.s

tests/test_iomanager.o: tests/test_iomanager.cpp.o

.PHONY : tests/test_iomanager.o

# target to build an object file
tests/test_iomanager.cpp.o:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cpp.o
.PHONY : tests/test_iomanager.cpp.o

tests/test_iomanager.i: tests/test_iomanager.cpp.i

.PHONY : tests/test_iomanager.i

# target to preprocess a source file
tests/test_iomanager.cpp.i:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cpp.i
.PHONY : tests/test_iomanager.cpp.i

tests/test_iomanager.s: tests/test_iomanager.cpp.s

.PHONY : tests/test_iomanager.s

# target to generate assembly for a file
tests/test_iomanager.cpp.s:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cpp.s
.PHONY : tests/test_iomanager.cpp.s

tests/test_schedule.o: tests/test_schedule.cpp.o

.PHONY : tests/test_schedule.o

# target to build an object file
tests/test_schedule.cpp.o:
	$(MAKE) -f CMakeFiles/test_schedule.dir/build.make CMakeFiles/test_schedule.dir/tests/test_schedule.cpp.o
.PHONY : tests/test_schedule.cpp.o

tests/test_schedule.i: tests/test_schedule.cpp.i

.PHONY : tests/test_schedule.i

# target to preprocess a source file
tests/test_schedule.cpp.i:
	$(MAKE) -f CMakeFiles/test_schedule.dir/build.make CMakeFiles/test_schedule.dir/tests/test_schedule.cpp.i
.PHONY : tests/test_schedule.cpp.i

tests/test_schedule.s: tests/test_schedule.cpp.s

.PHONY : tests/test_schedule.s

# target to generate assembly for a file
tests/test_schedule.cpp.s:
	$(MAKE) -f CMakeFiles/test_schedule.dir/build.make CMakeFiles/test_schedule.dir/tests/test_schedule.cpp.s
.PHONY : tests/test_schedule.cpp.s

tests/test_socket.o: tests/test_socket.cpp.o

.PHONY : tests/test_socket.o

# target to build an object file
tests/test_socket.cpp.o:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cpp.o
.PHONY : tests/test_socket.cpp.o

tests/test_socket.i: tests/test_socket.cpp.i

.PHONY : tests/test_socket.i

# target to preprocess a source file
tests/test_socket.cpp.i:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cpp.i
.PHONY : tests/test_socket.cpp.i

tests/test_socket.s: tests/test_socket.cpp.s

.PHONY : tests/test_socket.s

# target to generate assembly for a file
tests/test_socket.cpp.s:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cpp.s
.PHONY : tests/test_socket.cpp.s

tests/test_tcp_server.o: tests/test_tcp_server.cpp.o

.PHONY : tests/test_tcp_server.o

# target to build an object file
tests/test_tcp_server.cpp.o:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cpp.o
.PHONY : tests/test_tcp_server.cpp.o

tests/test_tcp_server.i: tests/test_tcp_server.cpp.i

.PHONY : tests/test_tcp_server.i

# target to preprocess a source file
tests/test_tcp_server.cpp.i:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cpp.i
.PHONY : tests/test_tcp_server.cpp.i

tests/test_tcp_server.s: tests/test_tcp_server.cpp.s

.PHONY : tests/test_tcp_server.s

# target to generate assembly for a file
tests/test_tcp_server.cpp.s:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cpp.s
.PHONY : tests/test_tcp_server.cpp.s

tests/test_thread.o: tests/test_thread.cpp.o

.PHONY : tests/test_thread.o

# target to build an object file
tests/test_thread.cpp.o:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cpp.o
.PHONY : tests/test_thread.cpp.o

tests/test_thread.i: tests/test_thread.cpp.i

.PHONY : tests/test_thread.i

# target to preprocess a source file
tests/test_thread.cpp.i:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cpp.i
.PHONY : tests/test_thread.cpp.i

tests/test_thread.s: tests/test_thread.cpp.s

.PHONY : tests/test_thread.s

# target to generate assembly for a file
tests/test_thread.cpp.s:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cpp.s
.PHONY : tests/test_thread.cpp.s

tests/test_timer.o: tests/test_timer.cpp.o

.PHONY : tests/test_timer.o

# target to build an object file
tests/test_timer.cpp.o:
	$(MAKE) -f CMakeFiles/test_timer.dir/build.make CMakeFiles/test_timer.dir/tests/test_timer.cpp.o
.PHONY : tests/test_timer.cpp.o

tests/test_timer.i: tests/test_timer.cpp.i

.PHONY : tests/test_timer.i

# target to preprocess a source file
tests/test_timer.cpp.i:
	$(MAKE) -f CMakeFiles/test_timer.dir/build.make CMakeFiles/test_timer.dir/tests/test_timer.cpp.i
.PHONY : tests/test_timer.cpp.i

tests/test_timer.s: tests/test_timer.cpp.s

.PHONY : tests/test_timer.s

# target to generate assembly for a file
tests/test_timer.cpp.s:
	$(MAKE) -f CMakeFiles/test_timer.dir/build.make CMakeFiles/test_timer.dir/tests/test_timer.cpp.s
.PHONY : tests/test_timer.cpp.s

tests/test_uri.o: tests/test_uri.cpp.o

.PHONY : tests/test_uri.o

# target to build an object file
tests/test_uri.cpp.o:
	$(MAKE) -f CMakeFiles/test_uri.dir/build.make CMakeFiles/test_uri.dir/tests/test_uri.cpp.o
.PHONY : tests/test_uri.cpp.o

tests/test_uri.i: tests/test_uri.cpp.i

.PHONY : tests/test_uri.i

# target to preprocess a source file
tests/test_uri.cpp.i:
	$(MAKE) -f CMakeFiles/test_uri.dir/build.make CMakeFiles/test_uri.dir/tests/test_uri.cpp.i
.PHONY : tests/test_uri.cpp.i

tests/test_uri.s: tests/test_uri.cpp.s

.PHONY : tests/test_uri.s

# target to generate assembly for a file
tests/test_uri.cpp.s:
	$(MAKE) -f CMakeFiles/test_uri.dir/build.make CMakeFiles/test_uri.dir/tests/test_uri.cpp.s
.PHONY : tests/test_uri.cpp.s

tests/test_utils.o: tests/test_utils.cpp.o

.PHONY : tests/test_utils.o

# target to build an object file
tests/test_utils.cpp.o:
	$(MAKE) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/tests/test_utils.cpp.o
.PHONY : tests/test_utils.cpp.o

tests/test_utils.i: tests/test_utils.cpp.i

.PHONY : tests/test_utils.i

# target to preprocess a source file
tests/test_utils.cpp.i:
	$(MAKE) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/tests/test_utils.cpp.i
.PHONY : tests/test_utils.cpp.i

tests/test_utils.s: tests/test_utils.cpp.s

.PHONY : tests/test_utils.s

# target to generate assembly for a file
tests/test_utils.cpp.s:
	$(MAKE) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/tests/test_utils.cpp.s
.PHONY : tests/test_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... echo_server"
	@echo "... test_application"
	@echo "... test_env"
	@echo "... test_daemon"
	@echo "... test_http_connection"
	@echo "... test_http_server"
	@echo "... test_tcp_server"
	@echo "... test_http_parser"
	@echo "... test_http"
	@echo "... test"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test_uri"
	@echo "... test_coroutine"
	@echo "... my_http_server"
	@echo "... test_addr"
	@echo "... test_bytearray"
	@echo "... test_config"
	@echo "... test_schedule"
	@echo "... test_utils"
	@echo "... test_iomanager"
	@echo "... test_thread"
	@echo "... test_timer"
	@echo "... test_hook"
	@echo "... kit_server"
	@echo "... test_socket"
	@echo "... ab_example/my_http_server.o"
	@echo "... ab_example/my_http_server.i"
	@echo "... ab_example/my_http_server.s"
	@echo "... example/echo_server.o"
	@echo "... example/echo_server.i"
	@echo "... example/echo_server.s"
	@echo "... kit_server/Log.o"
	@echo "... kit_server/Log.i"
	@echo "... kit_server/Log.s"
	@echo "... kit_server/address.o"
	@echo "... kit_server/address.i"
	@echo "... kit_server/address.s"
	@echo "... kit_server/application.o"
	@echo "... kit_server/application.i"
	@echo "... kit_server/application.s"
	@echo "... kit_server/bytearray.o"
	@echo "... kit_server/bytearray.i"
	@echo "... kit_server/bytearray.s"
	@echo "... kit_server/config.o"
	@echo "... kit_server/config.i"
	@echo "... kit_server/config.s"
	@echo "... kit_server/coroutine.o"
	@echo "... kit_server/coroutine.i"
	@echo "... kit_server/coroutine.s"
	@echo "... kit_server/daemon.o"
	@echo "... kit_server/daemon.i"
	@echo "... kit_server/daemon.s"
	@echo "... kit_server/env.o"
	@echo "... kit_server/env.i"
	@echo "... kit_server/env.s"
	@echo "... kit_server/fdmanager.o"
	@echo "... kit_server/fdmanager.i"
	@echo "... kit_server/fdmanager.s"
	@echo "... kit_server/hook.o"
	@echo "... kit_server/hook.i"
	@echo "... kit_server/hook.s"
	@echo "... kit_server/http/http.o"
	@echo "... kit_server/http/http.i"
	@echo "... kit_server/http/http.s"
	@echo "... kit_server/http/http11_parser.rl.o"
	@echo "... kit_server/http/http11_parser.rl.i"
	@echo "... kit_server/http/http11_parser.rl.s"
	@echo "... kit_server/http/http_connection.o"
	@echo "... kit_server/http/http_connection.i"
	@echo "... kit_server/http/http_connection.s"
	@echo "... kit_server/http/http_parser.o"
	@echo "... kit_server/http/http_parser.i"
	@echo "... kit_server/http/http_parser.s"
	@echo "... kit_server/http/http_server.o"
	@echo "... kit_server/http/http_server.i"
	@echo "... kit_server/http/http_server.s"
	@echo "... kit_server/http/http_session.o"
	@echo "... kit_server/http/http_session.i"
	@echo "... kit_server/http/http_session.s"
	@echo "... kit_server/http/httpclient_parser.rl.o"
	@echo "... kit_server/http/httpclient_parser.rl.i"
	@echo "... kit_server/http/httpclient_parser.rl.s"
	@echo "... kit_server/http/servlet.o"
	@echo "... kit_server/http/servlet.i"
	@echo "... kit_server/http/servlet.s"
	@echo "... kit_server/iomanager.o"
	@echo "... kit_server/iomanager.i"
	@echo "... kit_server/iomanager.s"
	@echo "... kit_server/mutex.o"
	@echo "... kit_server/mutex.i"
	@echo "... kit_server/mutex.s"
	@echo "... kit_server/scheduler.o"
	@echo "... kit_server/scheduler.i"
	@echo "... kit_server/scheduler.s"
	@echo "... kit_server/socket.o"
	@echo "... kit_server/socket.i"
	@echo "... kit_server/socket.s"
	@echo "... kit_server/socket_stream.o"
	@echo "... kit_server/socket_stream.i"
	@echo "... kit_server/socket_stream.s"
	@echo "... kit_server/stream.o"
	@echo "... kit_server/stream.i"
	@echo "... kit_server/stream.s"
	@echo "... kit_server/tcp_server.o"
	@echo "... kit_server/tcp_server.i"
	@echo "... kit_server/tcp_server.s"
	@echo "... kit_server/thread.o"
	@echo "... kit_server/thread.i"
	@echo "... kit_server/thread.s"
	@echo "... kit_server/timer.o"
	@echo "... kit_server/timer.i"
	@echo "... kit_server/timer.s"
	@echo "... kit_server/uri.rl.o"
	@echo "... kit_server/uri.rl.i"
	@echo "... kit_server/uri.rl.s"
	@echo "... kit_server/util.o"
	@echo "... kit_server/util.i"
	@echo "... kit_server/util.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
	@echo "... tests/test_addr.o"
	@echo "... tests/test_addr.i"
	@echo "... tests/test_addr.s"
	@echo "... tests/test_application.o"
	@echo "... tests/test_application.i"
	@echo "... tests/test_application.s"
	@echo "... tests/test_bytearray.o"
	@echo "... tests/test_bytearray.i"
	@echo "... tests/test_bytearray.s"
	@echo "... tests/test_config.o"
	@echo "... tests/test_config.i"
	@echo "... tests/test_config.s"
	@echo "... tests/test_coroutine.o"
	@echo "... tests/test_coroutine.i"
	@echo "... tests/test_coroutine.s"
	@echo "... tests/test_daemon.o"
	@echo "... tests/test_daemon.i"
	@echo "... tests/test_daemon.s"
	@echo "... tests/test_env.o"
	@echo "... tests/test_env.i"
	@echo "... tests/test_env.s"
	@echo "... tests/test_hook.o"
	@echo "... tests/test_hook.i"
	@echo "... tests/test_hook.s"
	@echo "... tests/test_http.o"
	@echo "... tests/test_http.i"
	@echo "... tests/test_http.s"
	@echo "... tests/test_http_connection.o"
	@echo "... tests/test_http_connection.i"
	@echo "... tests/test_http_connection.s"
	@echo "... tests/test_http_parser.o"
	@echo "... tests/test_http_parser.i"
	@echo "... tests/test_http_parser.s"
	@echo "... tests/test_http_server.o"
	@echo "... tests/test_http_server.i"
	@echo "... tests/test_http_server.s"
	@echo "... tests/test_iomanager.o"
	@echo "... tests/test_iomanager.i"
	@echo "... tests/test_iomanager.s"
	@echo "... tests/test_schedule.o"
	@echo "... tests/test_schedule.i"
	@echo "... tests/test_schedule.s"
	@echo "... tests/test_socket.o"
	@echo "... tests/test_socket.i"
	@echo "... tests/test_socket.s"
	@echo "... tests/test_tcp_server.o"
	@echo "... tests/test_tcp_server.i"
	@echo "... tests/test_tcp_server.s"
	@echo "... tests/test_thread.o"
	@echo "... tests/test_thread.i"
	@echo "... tests/test_thread.s"
	@echo "... tests/test_timer.o"
	@echo "... tests/test_timer.i"
	@echo "... tests/test_timer.s"
	@echo "... tests/test_uri.o"
	@echo "... tests/test_uri.i"
	@echo "... tests/test_uri.s"
	@echo "... tests/test_utils.o"
	@echo "... tests/test_utils.i"
	@echo "... tests/test_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

